### ISSUE TITLE
Allow enhancing videos with properties from VideoObject schema

### ISSUE THREAD

**Issue by cwillems** [openHPI/videoplayer#3]
See http://schema.org/VideoObject

Data for video player initialization should be able to hold metadata for arbitrary properties defined in the VideoObject schema.

Metadata should be rendered as JSON-LD (JSON Linked Data).

**Comment by jprberlin** [comment]
@team: please support this nearby.

**Comment by jprberlin** [comment]
@cwillems Can you provide an example withe the fields we can provide in openHPI?
