### ISSUE TITLE
Fullscreen is not working on iPad 

### ISSUE THREAD

**Issue by jprberlin** [openHPI/videoplayer#4]
Video scales, buts stays within the layout of the embedding page. needs to be positioned absolut.

**Comment by jonathanherdt** [comment]
Was already positioned absolutely. I changed it to 'fixed' with a z-index of 1050. This works but has the disadvantage that we can still "scroll" content. To fix this, I am hard-setting `position: fixed` on the body. When exiting full-screen mode, position will be reset to its old value.
