### ISSUE TITLE
Semantics of fallback switch

### ISSUE THREAD

**Issue by cwillems** [openHPI/videoplayer#9]
When i watch a video with dual stream, and have a single stream fallback available, the button shows the icon for dual stream while being in dual stream mode (and the single stream icon when in single stream mode).
![screenshot_dual_stream](https://user-images.githubusercontent.com/1996660/29413319-4a7010bc-835c-11e7-80b2-8df48554f9a7.png)
I would expect the button to show, what it will do if i click it... @jprberlin your opinion?

**Comment by jprberlin** [comment]
I would also suggest to toggle the button states

**Comment by jonathanherdt** [comment]
Done.
